name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Deploy to EC2
        env:
          SS: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USERNAME: ${{ secrets.EC2_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > /tmp/aws_ec2_key.pem
          chmod 600 /tmp/aws_ec2_key.pem
          ssh -o StrictHostKeyChecking=no -i /tmp/aws_ec2_key.pem $USERNAME@$HOST << 'EOF'
            cd /home/ubuntu/gridiron-backend
            git pull origin master
            npm install
            npm run build
            pm2 restart backend
          EOF
